// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-candidates.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function sbForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_candidates_default = defineTool({
  name: "list_candidates",
  title: "List candidates",
  description: "List candidates from the signed-in user's driving school. Results are scoped by tenant RLS. Supports optional name/personal-number search and pagination.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive substring matched against first name, last name, or personal number."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50)."),
    offset: z.number().int().min(0).optional().describe("Row offset for pagination (default 0).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ search, limit, offset }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = sbForUser(ctx);
    const take = limit ?? 50;
    const skip = offset ?? 0;
    let q = sb.from("candidates").select(
      "id, emri, mbiemri, numri_personal, telefon, email, kategoria, statusi, nr_rendor, data_regjistrimit",
      { count: "exact" }
    ).order("data_regjistrimit", { ascending: false }).range(skip, skip + take - 1);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`emri.ilike.${s},mbiemri.ilike.${s},numri_personal.ilike.${s}`);
    }
    const { data, error, count } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ count, rows: data }) }],
      structuredContent: { count: count ?? 0, rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-candidate.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sbForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_candidate_default = defineTool2({
  name: "get_candidate",
  title: "Get candidate",
  description: "Fetch full details for one candidate by id, including payments, lessons, and exams. Scoped by RLS.",
  inputSchema: {
    id: z2.string().uuid().describe("Candidate id (uuid).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = sbForUser2(ctx);
    const [candidate, payments, lessons, exams] = await Promise.all([
      sb.from("candidates").select("*").eq("id", id).maybeSingle(),
      sb.from("candidate_payments").select("*").eq("candidate_id", id).order("data_pageses", { ascending: false }),
      sb.from("candidate_lessons").select("*").eq("candidate_id", id).order("data_or\xEBs", { ascending: false }),
      sb.from("candidate_exams").select("*").eq("candidate_id", id).order("data_provimit", { ascending: false })
    ]);
    if (candidate.error)
      return { content: [{ type: "text", text: candidate.error.message }], isError: true };
    if (!candidate.data)
      return { content: [{ type: "text", text: "Candidate not found" }], isError: true };
    const payload = {
      candidate: candidate.data,
      payments: payments.data ?? [],
      lessons: lessons.data ?? [],
      exams: exams.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-registrations.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sbForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_registrations_default = defineTool3({
  name: "list_registrations",
  title: "List online registrations",
  description: "List online registration requests submitted through the public site. Scoped by tenant RLS.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional(),
    offset: z3.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit, offset }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = sbForUser3(ctx);
    const take = limit ?? 50;
    const skip = offset ?? 0;
    const { data, error, count } = await sb.from("registrations").select("*", { count: "exact" }).order("created_at", { ascending: false }).range(skip, skip + take - 1);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ count, rows: data }) }],
      structuredContent: { count: count ?? 0, rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-vehicles.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sbForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_vehicles_default = defineTool4({
  name: "list_vehicles",
  title: "List vehicles",
  description: "List the driving school's vehicles (make, model, plate, category, inspection/insurance dates). Scoped by RLS.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = sbForUser4(ctx);
    const { data, error } = await sb.from("vehicles").select("*").order("created_at", { ascending: false });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-employees.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sbForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_employees_default = defineTool5({
  name: "list_employees",
  title: "List employees",
  description: "List employees (instructors and staff) of the driving school. Scoped by RLS.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = sbForUser5(ctx);
    const { data, error } = await sb.from("employees").select("*").order("created_at", { ascending: false });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-licenses.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sbForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_licenses_default = defineTool6({
  name: "list_licenses",
  title: "List driving-school licenses",
  description: "List the driving school's category licenses (numbers and expiry dates). Scoped by RLS.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = sbForUser6(ctx);
    const { data, error } = await sb.from("licenses").select("*").order("kategoria");
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hgbwdywlrgnpzfhviovs";
var mcp_default = defineMcp({
  name: "auto-shkolla-visi-mcp",
  title: "Auto Shkolla Visi MCP",
  version: "0.1.0",
  instructions: "Read-only tools for a driving-school management app. Callers act as the signed-in user (admin, instructor, or candidate) and only see data from their own driving school (tenant). Use list_candidates/get_candidate for people, list_registrations for online sign-ups, and list_vehicles/list_employees/list_licenses for fleet and staff info.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_candidates_default, get_candidate_default, list_registrations_default, list_vehicles_default, list_employees_default, list_licenses_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
